### ISSUE TITLE
Add a Link to the explorer in the top menu on the website. 

### ISSUE THREAD

**Issue by Davbit1** [VeriBlock/community#15]
The Link to the explorer is hard to find. 
Please add it to the top menu or at least somewhere on the website that it is easier to reach

**Comment by paucasafont** [comment]
Added explorer link to the top menu (More -> Explorer).

![image](https://user-images.githubusercontent.com/13179843/131359561-4e4c6ef0-a8d1-4c5e-b144-781bc3498906.png)
