### ISSUE TITLE
Fix bug where APM GUI is inaccessible when not specifying the index.html file path in the url

### ISSUE THREAD

**Issue by Fridtjon** [VeriBlock/community#16]
## Summary
The full index file path (http://localhost:8080/index.html) must be specified to access the APM GUI. Page refresh does not work after accessing the GUI this way.

## Steps to reproduce
1. Have a running instance of APM
2. Enter http://localhost:8080
3. Notice that page could not be found
4. Enter http://localhost:8080/index.html
5. Notice that GUI loads
6. Refresh page (`F5` / `CMD + R`)
7. Notice that page could not be found

## Current behavior
- The full index path must be used to access the APM GUI
- Page refresh breaks page

## Expected behavior
- APM GUI should be accessible through http://localhost:8080

## Notes
This was working a few weeks ago, suggesting that this bug is due to a recent change

**Comment by BernatCarbo** [comment]
Should be solved with: https://github.com/VeriBlock/nodecore/commit/c1f459557cef58f17e999e3947490e0080591b9c
